logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}
spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/edificios_crud
#    username: postgres
#    password: postgres
  datasource:
    url: jdbc:sqlite:edificios_crud.db
    driver-class-name: org.sqlite.JDBC
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    defer-datasource-initialization: true
  mustache:
    check-template-location: false
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.flowingcode